name: Get Subscription Weekly

on:
  schedule:
    - cron: '0 3 * * *'  # 北京时间每周日凌晨执行
  workflow_dispatch: # 允许手动触发

env:
  # time zone
  TZ: Asia/Shanghai
  ENABLE_SPECIAL_PROTOCOLS: 0

permissions:
  contents: write

jobs:
  execute-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip3 install pyYAML requests
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Collect Subscribe
      id: collect
      run: |
        python -u subscribe/collect.py -a -d 3000
      
    - name: Create/Update Gist
      env:
        GH_TOKEN: ${{ secrets.PAT }}
      run: |
        cd data
        gh gist edit 64272563c2d4779b5ca0a28ead4c603a  --add "clash.yaml"
