name: Get Subscription Weekly

on:
  schedule:
    - cron: '0 16 * * 6'  # 北京时间每周日凌晨执行
  workflow_dispatch: # 允许手动触发

permissions:
  contents: write

jobs:
  execute-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip3 install pyYAML requests
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Collect Subscribe
      id: collect
      run: |
        python -u subscribe/collect.py
      
    - name: Create/Update Gist
      env:
        GH_TOKEN: ${{ secrets.PAT }}
      run: |
        cd data
        gh gist edit d557eb147718f11f262108474e2156c1  --add "proxies.yaml"
        gh gist edit d557eb147718f11f262108474e2156c1  --add "subscribes.txt"
        gh gist edit d557eb147718f11f262108474e2156c1  --add "domains.txt"
        gh gist edit d557eb147718f11f262108474e2156c1  --add "valid-domains.txt"
